# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 06:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('level', models.CharField(max_length=12, null=True)),
                ('office', models.CharField(max_length=24, null=True)),
                ('district', models.CharField(blank=True, max_length=24, null=True)),
                ('status', models.CharField(max_length=12, null=True)),
                ('profile_url', models.URLField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('primary_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DNCGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=36, null=True)),
            ],
            options={
                'ordering': ('abbr',),
            },
        ),
        migrations.CreateModel(
            name='Footnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=3, null=True)),
                ('firstname', models.CharField(blank=True, max_length=36, null=True)),
                ('middlename', models.CharField(blank=True, max_length=36, null=True)),
                ('lastname', models.CharField(blank=True, max_length=36, null=True)),
                ('name_suffix', models.CharField(blank=True, max_length=24, null=True)),
                ('nickname', models.CharField(blank=True, max_length=24, null=True)),
                ('party', models.CharField(blank=True, max_length=1, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('district', models.CharField(blank=True, max_length=24, null=True)),
                ('in_office', models.BooleanField()),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('fax', models.CharField(blank=True, max_length=16, null=True)),
                ('website', models.CharField(blank=True, max_length=128, null=True)),
                ('webform', models.CharField(blank=True, max_length=128, null=True)),
                ('congress_office', models.CharField(blank=True, max_length=128, null=True)),
                ('bioguide_id', models.CharField(max_length=8, unique=True)),
                ('votesmart_id', models.CharField(max_length=6)),
                ('fec_id', models.CharField(max_length=10)),
                ('govtrack_id', models.CharField(max_length=8)),
                ('crp_id', models.CharField(max_length=10)),
                ('twitter_id', models.CharField(blank=True, max_length=24, null=True)),
                ('congresspedia_url', models.CharField(blank=True, max_length=128, null=True)),
                ('youtube_url', models.CharField(blank=True, max_length=128, null=True)),
                ('facebook_id', models.CharField(blank=True, max_length=128, null=True)),
                ('official_rss', models.CharField(blank=True, max_length=64, null=True)),
                ('senate_class', models.CharField(blank=True, max_length=3, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('oc_email', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ('lastname',),
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(blank=True, max_length=24, null=True)),
                ('name', models.CharField(blank=True, max_length=36, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('fax', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresidentialCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=36)),
                ('fips_state', models.CharField(default='ZZ', max_length=2)),
                ('census_region_name', models.CharField(default='ZZ', max_length=12)),
            ],
            options={
                'ordering': ('state',),
            },
        ),
        migrations.CreateModel(
            name='StateLegislator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('chamber', models.CharField(max_length=16)),
                ('leg_id', models.CharField(max_length=16)),
                ('level', models.CharField(max_length=16)),
                ('district', models.CharField(blank=True, max_length=24, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('first_name', models.CharField(blank=True, max_length=36, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=36, null=True)),
                ('last_name', models.CharField(blank=True, max_length=36, null=True)),
                ('full_name', models.CharField(blank=True, max_length=48, null=True)),
                ('party', models.CharField(blank=True, max_length=24, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('suffixes', models.CharField(blank=True, max_length=24, null=True)),
                ('url', models.URLField(blank=True, max_length=128, null=True)),
                ('votesmart_id', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('transparencydata_id', models.CharField(blank=True, max_length=48, null=True)),
                ('all_ids', models.CharField(blank=True, max_length=256, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('offices', models.ManyToManyField(to='adrestia.Office')),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=16)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='delegate',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adrestia.PresidentialCandidate'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='footnotes',
            field=models.ManyToManyField(to='adrestia.Footnote'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adrestia.DNCGroup'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='legislator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adrestia.Legislator', to_field='bioguide_id'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adrestia.State'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adrestia.State'),
        ),
    ]
