# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='legislator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adrestia.Legislator', to_field='bioguide_id'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='state_legislator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adrestia.StateLegislator', to_field='leg_id'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='state_legislator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adrestia.StateLegislator', to_field='leg_id'),
        ),
        migrations.AlterField(
            model_name='statelegislator',
            name='leg_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
