# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0002_auto_20160402_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statelegislator',
            name='district',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
