# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0003_auto_20160404_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='district',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
