# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0004_auto_20160404_0321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footnote',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='legislator',
            name='bioguide_id',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='crp_id',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='fec_id',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='govtrack_id',
            field=models.CharField(db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='votesmart_id',
            field=models.CharField(db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='webform',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='statelegislator',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='statelegislator',
            name='leg_id',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='statelegislator',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='statelegislator',
            name='transparencydata_id',
            field=models.CharField(blank=True, db_index=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='statelegislator',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='statelegislator',
            name='votesmart_id',
            field=models.CharField(db_index=True, max_length=6),
        ),
    ]
