# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0005_auto_20160405_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='opponents',
            field=models.ManyToManyField(to='adrestia.Candidate'),
        ),
    ]
