# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0006_delegate_opponents'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='general_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='primary_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='level',
            field=models.CharField(choices=[(None, 'Any Level'), ('Federal', 'Federal'), ('State', 'State')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='office',
            field=models.CharField(choices=[(None, 'Any Chamber'), ('Senate', 'Senate'), ('House', 'House')], max_length=24, null=True),
        ),
    ]
