# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0007_auto_20160411_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='running',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='serving',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
