# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 00:54
from __future__ import unicode_literals

import adrestia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0010_candidate_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=adrestia.models.make_digest),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='image_url',
            field=models.URLField(blank=True, help_text='This one is probably going to go away... use image, below', max_length=500, null=True),
        ),
    ]
