# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 20:56
from __future__ import unicode_literals

import adrestia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0011_auto_20160412_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, help_text='Enter a local image file her to upload', null=True, upload_to=adrestia.models.make_digest),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='image_url',
            field=models.URLField(blank=True, help_text='Enter an image URL here and the image will be uploaded', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='level',
            field=models.CharField(choices=[(None, 'Any Level'), ('Federal', 'Federal'), ('State', 'State')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
