# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0013_auto_20160412_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='level',
            field=models.CharField(choices=[(None, 'Any Level'), ('Federal', 'Federal'), ('State', 'State'), ('Local', 'Local')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='office',
            field=models.CharField(choices=[(None, 'Any Office'), ('Senate', 'Senate'), ('House', 'House'), ('Governor', 'Governor'), ('Lt. Governor', 'Lt. Governor'), ('Mayor', 'Mayor'), ('Secretary of State', 'Secretary of State')], max_length=24, null=True),
        ),
    ]
