# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0014_auto_20160413_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='webform_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('R', 'R'), ('AI', 'AI'), ('PF', 'PF'), ('G', 'G'), ('GI', 'GI'), ('IR', 'IR'), ('IP', 'IP'), ('R', 'R')], help_text='See for abbreviations: http://abcnews.go.com/Politics/party-abbreviations/story?id=10865978', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
