# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0015_auto_20160413_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='fax',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='website_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
