# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 00:32
from __future__ import unicode_literals

import adrestia.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0016_auto_20160413_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegateSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_pledged', models.IntegerField(default=0)),
                ('allocation_unpledged', models.IntegerField(default=0)),
                ('sanders_pledged', models.IntegerField(default=0)),
                ('sanders_unpledged', models.IntegerField(default=0)),
                ('clinton_pledged', models.IntegerField(default=0)),
                ('clinton_unpledged', models.IntegerField(default=0)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adrestia.State', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, help_text='Enter a local image file here to upload', null=True, upload_to=adrestia.models.make_digest),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(blank=True, choices=[('D', 'Democrat'), ('G', 'Green'), ('GI', 'Independent Green'), ('DFL', 'Minnesota Democratic-Farmer-Labor Party'), ('IR', 'Independent-Progressive'), ('IP', 'Independent Party'), ('AI', 'American Independent'), ('PF', 'Peace and Freedom'), ('R', 'Republican'), ('UN', 'Unaffiliated')], help_text='See for abbreviations: http://abcnews.go.com/Politics/party-abbreviations/story?id=10865978', max_length=2, null=True),
        ),
    ]
