# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0017_auto_20160418_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegatesummary',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adrestia.State'),
        ),
    ]
