# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0019_auto_20160418_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delegatesummary',
            options={'ordering': ('state__name',), 'verbose_name_plural': 'delegate summaries'},
        ),
        migrations.AlterModelOptions(
            name='dncgroup',
            options={'ordering': ('abbr',), 'verbose_name_plural': 'DNC Groups'},
        ),
        migrations.AlterModelOptions(
            name='presidentialcandidate',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='webform_url',
            field=models.URLField(blank=True, help_text='Enter URL of web form if available', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='district',
            field=models.CharField(blank=True, help_text='Fed or State house district name or number, Junior Seat or Senior Seat for Fed Senate, City for Mayor', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='facebook_id',
            field=models.CharField(blank=True, help_text='Use Facebook ID, not URL', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='image_url',
            field=models.URLField(blank=True, help_text='Enter image URL here and the image will be uploaded', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='legislator',
            field=models.ForeignKey(blank=True, help_text='Enter Legislator if this candidate is the incumbent', null=True, on_delete=django.db.models.deletion.CASCADE, to='adrestia.Legislator', to_field='bioguide_id'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional information displayed on page', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='office',
            field=models.CharField(choices=[(None, 'Any Office'), ('Senate', 'Senate'), ('House', 'House'), ('Governor', 'Governor'), ('Lt. Governor', 'Lt. Governor'), ('Mayor', 'Mayor'), ('Secretary of State', 'Secretary of State'), ('City Council', 'City Council'), ('County Council', 'County Council')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='primary_date',
            field=models.DateField(blank=True, help_text='Deprecated.  This field is ignored. See State.', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='profile_url',
            field=models.URLField(blank=True, help_text='Expat profile URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='running',
            field=models.BooleanField(help_text='Running for office or re-election'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='serving',
            field=models.BooleanField(help_text='Check this candidate is the incumbent'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state_legislator',
            field=models.ForeignKey(blank=True, help_text='Enter State Legislator if this candidate is the incumbent', null=True, on_delete=django.db.models.deletion.CASCADE, to='adrestia.StateLegislator', to_field='leg_id'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='twitter_id',
            field=models.CharField(blank=True, help_text='Use Twitter ID, not URL', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='winner',
            field=models.BooleanField(default=False, help_text='Check this if candidate has won their election'),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='oc_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='statelegislator',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
