# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 01:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0021_delegate_vote_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 11, 1, 4, 16, 183099, tzinfo=utc), help_text='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='endorsement_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='general_win',
            field=models.NullBooleanField(help_text='Check this if candidate has won their general election'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='primary_win',
            field=models.NullBooleanField(help_text='Check this if candidate has won their primary'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 11, 1, 4, 34, 983137, tzinfo=utc), help_text='Updated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='office',
            field=models.CharField(choices=[(None, 'Any Office'), ('Senate', 'Senate'), ('House', 'House'), ('Governor', 'Governor'), ('Lt. Governor', 'Lt. Governor'), ('Secretary of State', 'Secretary of State'), ('County Council', 'County Council'), ('Mayor', 'Mayor'), ('City Council', 'City Council'), ('Town Representative', 'Town Representative'), ('County Recorder', 'County Recorder'), ('County Commissioner', 'County Commissioner'), ('County Auditor', 'County Auditor'), ('County Legislature', 'County Legislature'), ('County Supervisor', 'County Supervisor'), ('City-County Council', 'City-County Council'), ('Alderman', 'Alderman'), ('Alderwoman', 'Alderwoman'), ('Justice of the Peace', 'Justice of the Peace'), ('Central Committee', 'Central Committee'), ('Neighborhood Council', 'Neighborhood Council'), ('Surrogate', 'Surrogate'), ('Freeholder', 'Freeholder')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(blank=True, choices=[('D', 'Democrat'), ('G', 'Green'), ('GI', 'Independent Green'), ('DFL', 'Minnesota Democratic-Farmer-Labor Party'), ('IR', 'Independent-Progressive'), ('IP', 'Independent Party'), ('PF', 'Peace and Freedom'), ('R', 'Republican'), ('UN', 'Unaffiliated')], help_text='See for abbreviations: http://abcnews.go.com/Politics/party-abbreviations/story?id=10865978', max_length=2, null=True),
        ),
    ]
