# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0022_auto_20160511_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
