# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrestia', '0023_auto_20160511_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='level',
            field=models.CharField(choices=[(None, 'Any Level'), ('Federal', 'Federal'), ('State', 'State'), ('County', 'County'), ('City', 'City'), ('Neighborhood', 'Neighborhood')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(blank=True, choices=[('D', 'Democrat'), ('G', 'Green'), ('GI', 'Independent Green'), ('DFL', 'Minnesota Democratic-Farmer-Labor Party'), ('IR', 'Independent-Progressive'), ('IP', 'Independent Party'), ('PF', 'Peace and Freedom'), ('R', 'Republican'), ('VPP', 'Vermont Progressive Party'), ('UN', 'Unaffiliated')], help_text='See for abbreviations: http://abcnews.go.com/Politics/party-abbreviations/story?id=10865978', max_length=3, null=True),
        ),
    ]
